# Generated by Django 4.2.6 on 2023-11-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/Profile_Images/avatar.jpg', upload_to='Profile_Images'),
        ),
    ]
